container:
  imageName: 
  imageTag: 
  image: straxseller/products-api:v0.1
  name: products-api

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

configs:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin
  USER_SERVICE_URI: 'http://local-users-api/users'

ingress:
  path: /products
  port: http
