replicaCount: 2

container:
  imageName: 
  imageTag: 
  image: straxseller/users-api:v0.1
  name: users-api

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

configs:
  POSTGRES_DB: users
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_PORT: '"5432"'

ingress:
  path: /users
  port: http