apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app
  name: products-api-configmap
  labels:
    app: products-api
data:
  POSTGRES_DB: products
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
