container:
  imageName: 
  imageTag: 
  image: straxseller/orders-api:v0.1
  name: orders-api

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

configs:
  POSTGRES_DB: orders
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_PORT: '"5432"'

ingress:
  path: /orders
  port: http