apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: users-service-destination
spec:
  host: local-users-api
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80