apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: users-api-virtual
spec:
  hosts:
    - local-users-api # ім'я Service до якого застосовується налаштування
  http:
    - route:
        - destination:
            host: local-users-api # ім'я Service до якого застосовується налаштування
      timeout: 5s
      retries:
        attempts: 2
        retryOn: 5xx
        perTryTimeout: 3s