apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app
  name: orders-api-configmap
  labels:
    app: orders-api
data:
  POSTGRES_DB: orders
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: postgres-orders
