postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "admin"
  fullnameOverride: "postgres"
  primary:
    initdb:
      scripts:
        init.sql: |
           CREATE DATABASE users;
           CREATE DATABASE orders;
           CREATE DATABASE products;
    persistence:
      mountPath: /var/lib/postgresql/data
      size: 2Gi
  readReplicas:
    persistence:
      enabled: false