apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: app
  name: postgres-orders-volume-claim
  labels:
    app: postgres-orders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
