apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: postgres-orders
  labels:
    app: postgres-orders
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-orders
