apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app
  name: users-api-configmap
  labels:
    app: users-api
data:
  POSTGRES_DB: users
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
