name: Build and Push docker images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./orders-api/Dockerfile
            tag: orders-api:v0.1
            context: ./orders-api/
          - dockerfile: ./products-api/Dockerfile
            tag: products-api:v0.1
            context: ./products-api/
          - dockerfile: ./users-api/Dockerfile
            tag: users-api:v0.1
            context: ./users-api/ 
          - dockerfile: ./frontend/Dockerfile
            tag: frontend:v0.1
            context: ./frontend/ 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push orders-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.tag }}
